# Generated by Django 4.0.6 on 2023-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_by', models.CharField(max_length=70)),
                ('upload_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Images/')),
            ],
        ),
    ]
